version: '3'
services:
  pgsql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${PGDB_NAME}
      POSTGRES_USER: ${PGDB_USER}
      POSTGRES_PASSWORD: ${PGDB_PASS}
    ports: [ "5432:5432" ]
    container_name: pgsql
    networks: [ skynet ]
  mongo:
    image: mongo:5.0.6
    container_name: mongo
    ports: [ "27017:27017" ]
    networks: [ skynet ]
  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    networks: [ skynet ]
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks: [ skynet ]
  sandbox:
    build:
      context: .
      args:
        target: sandbox
    image: sandbox
    container_name: sandbox
    environment:
      - APP_NAME=sandbox
    env_file: [ .env ]
    ports: [ "30000:3000" ]
    # command: 'sh -c "npm i && npm run start:dev sandbox"'
    # volumes: [ '.:/app', '/app/prisma', '/app/node_modules' ]
    networks: [ skynet ]
    depends_on: [ pgsql ]
  sandbox-prisma:
    build:
      context: .
      dockerfile: ./Dockerfile.prisma
      args:
        target: sandbox
    image: sandbox-prisma
    container_name: sandbox-prisma
    command: [ "npx", "prisma", "migrate", "reset", "--force" ]
    env_file: [ .env ]
    networks: [ skynet ]
    depends_on: [ pgsql ]
  partnership:
    build:
      context: .
      args:
        target: partnership
    image: partnership
    container_name: partnership
    environment:
      - APP_NAME=partnership
    env_file: [ .env ]
    ports: [ "30001:3000" ]
    # command: 'sh -c "npm i && npm run start:dev partnership"'
    # volumes: [ '.:/app', '/app/prisma', '/app/node_modules' ]
    networks: [ skynet ]
    depends_on: [ pgsql ]
  partnership-prisma:
    build:
      context: .
      dockerfile: ./Dockerfile.prisma
      args:
        target: partnership
    image: partnership-prisma
    container_name: partnership-prisma
    command: [ "npx", "prisma", "migrate", "reset", "--force" ]
    env_file: [ .env ]
    networks: [ skynet ]
    depends_on: [ pgsql ]
  partnership-dapr:
    image: 'daprio/daprd:1.6.0'
    container_name: partnership-dapr
    command: "./daprd -app-id partnership -app-port 3000 -placement-host-address placement:50005 -components-path /components -config /config.yaml"
    volumes:
      - './assets/dapr/.secrets.json:/opt/secrets.json'
      - './assets/dapr/components/secrets.yaml:/components/secrets.yaml'
      - './assets/dapr/components/state.yaml:/components/state.yaml'
      - './assets/dapr/components/pubsub.yaml:/components/pubsub.yaml'
      - './assets/dapr/config.yaml:/config.yaml'
    network_mode: 'service:partnership'
    depends_on: [ partnership, redis, mongo, pgsql, zipkin ]
networks:
  skynet:
    name: skynet
    driver: bridge
