version: '3'

networks:
  skynet:
    name: skynet
    driver: bridge

volumes:
  zen-pg-data:
    name: 'zen-pg-data'
  zen-mongo-data:
    name: 'zen-mongo-data'

services:
  pgsql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${PGDB_NAME}
      POSTGRES_USER: ${PGDB_USER}
      POSTGRES_PASSWORD: ${PGDB_PASS}
    ports: [ '5432:5432' ]
    volumes: [ 'zen-pg-data:/var/lib/postgresql/data' ]
    container_name: pgsql
    networks: [ skynet ]
  mongo:
    image: mongo:5.0.6
    container_name: mongo
    ports: [ "27017:27017" ]
    volumes: [ 'zen-mongo-data:/data/db' ]
    networks: [ skynet ]
  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    networks: [ skynet ]
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks: [ skynet ]
  sandbox:
    build:
      context: .
      args:
        target: sandbox
    image: zen/sandbox
    container_name: sandbox
    environment:
      - APP_NAME=sandbox
    env_file: [ .env ]
    ports: [ "30000:3000" ]
    # command: 'sh -c "npm i && npm run start:dev sandbox"'
    # volumes: [ '.:/app', '/app/prisma', '/app/node_modules' ]
    networks: [ skynet ]
    depends_on: [ pgsql ]
  sandbox-dapr:
    image: 'daprio/daprd:1.6.0'
    container_name: sandbox-dapr
    command: "./daprd -app-id sandbox -app-port 3000 -placement-host-address placement:50005 -components-path /components -config /config.yaml"
    volumes:
      - './assets/dapr/.secrets.json:/opt/secrets.json'
      - './assets/dapr/components/secrets.yaml:/components/secrets.yaml'
      - './assets/dapr/components/state.yaml:/components/state.yaml'
      - './assets/dapr/components/pubsub.yaml:/components/pubsub.yaml'
      - './assets/dapr/config.yaml:/config.yaml'
    network_mode: 'service:sandbox'
    depends_on: [ sandbox, redis, mongo, pgsql, zipkin ]
  sandbox-prisma:
    build:
      context: .
      dockerfile: ./Dockerfile.prisma
      args:
        target: sandbox
    image: sandbox-prisma
    container_name: sandbox-prisma
    command: [ "npx", "prisma", "migrate", "reset", "--force" ]
    env_file: [ .env ]
    networks: [ skynet ]
    depends_on: [ pgsql ]
  piracy:
    build:
      context: .
      args:
        target: piracy
    image: zen/piracy
    container_name: piracy
    environment:
      - APP_NAME=piracy
    env_file: [ .env ]
    ports: [ "30001:3000" ]
    # command: 'sh -c "npm i && npm run start:dev piracy"'
    # volumes: [ '.:/app', '/app/prisma', '/app/node_modules' ]
    networks: [ skynet ]
    depends_on: [ pgsql ]
  piracy-dapr:
    image: 'daprio/daprd:1.6.0'
    container_name: piracy-dapr
    command: "./daprd -app-id piracy -app-port 3000 -placement-host-address placement:50005 -components-path /components -config /config.yaml"
    volumes:
      - './assets/dapr/.secrets.json:/opt/secrets.json'
      - './assets/dapr/components/secrets.yaml:/components/secrets.yaml'
      - './assets/dapr/components/state.yaml:/components/state.yaml'
      - './assets/dapr/components/pubsub.yaml:/components/pubsub.yaml'
      - './assets/dapr/config.yaml:/config.yaml'
    network_mode: 'service:piracy'
    depends_on: [ piracy, redis, mongo, pgsql, zipkin ]
  piracy-prisma:
    build:
      context: .
      dockerfile: ./Dockerfile.prisma
      args:
        target: piracy
    image: piracy-prisma
    container_name: piracy-prisma
    command: [ "npx", "prisma", "migrate", "reset", "--force" ]
    env_file: [ .env ]
    networks: [ skynet ]
    depends_on: [ pgsql ]
