FROM node:16.13-alpine3.14 AS runtime
ARG target
WORKDIR /app
COPY package*.json ./
COPY apps/${target}/prisma ./prisma
RUN npm ci --only=production
RUN npm install -g ts-node
CMD ["npx", "prisma", "migrate", "deploy", "--force"]
