---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: '1'
    zipkin:
      endpointAddress: 'http://zipkin:9411/api/v2/spans'
# ---
# apiVersion: dapr.io/v1alpha1
# kind: Configuration
# metadata:
#   name: tracing
#   namespace: default
# spec:
#   tracing:
#     samplingRate: '1'
#     zipkin:
#       endpointAddress: 'http://jaeger:9412/api/v2/spans'
#     metric:
#       enabled: true
